export default function ProjectTemplateTwo({ project }) {
  console.log(project.projectName);
  return (
    <div className="ProjectTemplateTwo">
      <img
        src={project.image1}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image2}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image3}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image4}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image5}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image6}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image7}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image8}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image9}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image10}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image11}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
      <img
        src={project.image12}
        alt="project"
        className="ProjectTemplateTwo__Image"
      ></img>
    </div>
  );
}
