export default function ProjectTemplateThree({ project }) {
  return (
    <div className="ProjectTemplateThree">
      <img
        src={project.image1}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image2}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image3}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image4}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image5}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image6}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image7}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image8}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image9}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image10}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image11}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image12}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image13}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image14}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
      <img
        src={project.image15}
        alt="project"
        className="ProjectTemplateThree__Image"
      ></img>
    </div>
  );
}
